"""First run vs later runs in the WebGPU conditions of the paper's tables (Table 4 / S2 note).

usage: python first_vs_rest.py   (run from paper_jiim/; reads paper_benchmarks/analysis/timing.csv and the table tags
of scripts/make_tables.py, writes paper_benchmarks/analysis/first_vs_rest.txt)
Per condition x task: median of the first runs minus median of the per-case medians of runs 2..n.
"""
import csv, sys
from pathlib import Path

sys.path.insert(0, "scripts")
import make_tables as mt  # noqa: E402


def main():
    rows = [r for r in csv.DictReader(open("paper_benchmarks/analysis/timing.csv", encoding="utf-8")) if r["tag"] in mt.TAGS]
    rows = mt.drop_superseded(rows)
    d = sorted((float(r["first_median_s"]) - float(r["rest_median_s"]), r["tag"], r["task"]) for r in rows if r["rest_median_s"])
    out = ["# first-run median minus later-runs median, WebGPU conditions of Table 4 / S2 (generated by first_vs_rest.py)"]
    out += [f"{v:+.4f} s  {tag}  {task}" for v, tag, task in d]
    out += [f"range: {d[0][0]:+.4f} .. {d[-1][0]:+.4f} s"]
    Path("paper_benchmarks/analysis/first_vs_rest.txt").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(out[-1])


if __name__ == "__main__":
    main()
